grafico_porcentaje/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('registro.urls', namespace='registro')),
]

registro/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from registro import views


urlpatterns = patterns('',
    url(r'^$', views.Consultar.as_view(), name='consultar'),
    url(r'^registrar$', views.Registrar.as_view(), name='registrar'),
    url(r'^editar/(?P<pk>\d+)$', views.Editar.as_view(), name='editar'),
    url(r'^borrar/(?P<pk>\d+)$', views.Borrar.as_view(), name='borrar'),
)

registro/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse


class Proyecto(models.Model):
    """
    Modelo que contiene los campos de un Proyecto.
    """
    nombre = models.CharField(max_length=200)
    actividad_1 = models.IntegerField()
    actividad_2 = models.IntegerField()

    def total(self):
        """
        Función que suma los porcentajes de cada actividad
        y retorna el total de la operación.
        """
        total = self.actividad_1+self.actividad_2
        return total

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('registro:editar', kwargs={'pk': self.pk})

registro/forms.py
# -*- coding: utf-8 -*-
from django import forms
from registro.models import Proyecto
from django.forms import (
    TextInput, CharField, Select, RadioSelect, Textarea, CheckboxInput, DateTimeField
)


class ProyectoForm(forms.ModelForm):
    """
    Formulario que maneja los campos de un Proyecto.
    """
    nombre = forms.CharField(label='Nombre del Proyecto', widget=TextInput(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
    }), required = True)

    actividad_1 = forms.CharField(label='Actividad 1 %', widget=TextInput(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
        'value':'0',
    }), required = True)

    actividad_2 = forms.CharField(label='Actividad 2 %', widget=TextInput(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
        'value':'0',
    }), required = True)

    class Meta:

        model = Proyecto
        fields = '__all__'

registro/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from registro.models import Proyecto
from forms import ProyectoForm


class Consultar(ListView):
    """
    Clase que permite listar los proyectos.
    """
    model = Proyecto


class Registrar(CreateView):
    """
    Clase que permite registrar un proyecto.
    """
    model = Proyecto
    form_class = ProyectoForm
    success_url = reverse_lazy('registro:consultar')


class Editar(UpdateView):
    """
    Clase que permite editar los datos de un proyecto registrado.
    """
    model = Proyecto
    form_class = ProyectoForm
    success_url = reverse_lazy('registro:consultar')


class Borrar(DeleteView):
    """
    Clase que borrar un proyecto registrado.
    """
    model = Proyecto
    success_url = reverse_lazy('registro:consultar')

registro/templates/registro/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>
      {% block titulo %}Base{% endblock %}
    </title>
    {% load staticfiles %}
    <!-- Bootstrap Styles - css
    ================================================== -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- Styles - css
    ================================================== -->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet">
    <!-- Others - js
    ================================================== -->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <!-- Jquery - js
    ================================================== -->
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <!-- Bootstrap - js
    ================================================== -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Bug fix - js
    ================================================== -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </head>
  <body>
    
    <!-- Fixed navbar
    ================================================== -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'registro:consultar' %}">Mi proyecto</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="glyphicon glyphicon-cog"></i>
                &nbsp;Gestión <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="{% url 'registro:registrar' %}">
                    <i class="glyphicon glyphicon-list"></i>
                    &nbsp;Registrar proyecto
                  </a>
                </li>
                <li>
                  <a href="{% url 'registro:consultar' %}">
                    <i class="glyphicon glyphicon-list"></i>
                    &nbsp;Listar proyectos
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav><!-- End navbar -->

    <br />
    <br />
    <br />

    <div class="container theme-showcase" role="main">
      <div class="well">
      {% block cuerpo %}
      {% endblock %}
      </div>
    </div> <!-- /container -->

  </body>
</html>

registro/templates/registro/proyecto_confirm_delete.html
{% extends "registro/base.html" %}
{% block titulo %}Borrar proyecto{% endblock %}
{% block cuerpo %}
<h1>Borrar proyecto</h1>
<form method="post">{% csrf_token %}
  ¿Está seguro que desea eliminar a "{{ object }}"?
  <button class="btn btn-danger" type="submit">Borrar</button>
</form>
{% endblock %}

registro/templates/registro/proyecto_form.html
{% extends "registro/base.html" %}
{% block titulo %}Registrar proyecto{% endblock %}
{% block cuerpo %}
<h1>Registrar proyecto</h1>
<br />
<form method="post">{% csrf_token %}
  <b>{{ form.nombre.label }}</b>
  {{ form.nombre }}
  {% if form.nombre.errors %}
    <p>{{ form.nombre.errors}}</p>
  {% endif %}
  <br />
  <br />
  <b>{{ form.actividad_1.label }}</b>
  {{ form.actividad_1 }}
  {% if form.actividad_1.errors %}
    <p>{{ form.actividad_1.errors}}</p>
  {% endif %}
  <br />
  <br />
  <b>{{ form.actividad_2.label }}</b>
  {{ form.actividad_2 }}
  {% if form.actividad_2.errors %}
    <p>{{ form.actividad_2.errors}}</p>
  {% endif %}
  <br />
  <br />
  <button class="btn btn-success" type="submit">Guardar</button>
</form>
{% endblock %}

registro/templates/registro/proyecto_list.html
{% extends "registro/base.html" %}
{% block titulo %}Lista de Proyectos{% endblock %}
{% block cuerpo %}
<h1>Lista de Proyectos</h1>
{% if object_list %}
  {% for proyecto in object_list %}
  <div class="well well-white">
    <b>Nombre del proyecto:</b> {{ proyecto.nombre }}
    <br />
    <br />
    <b>Actividad 1 - Avance:</b> {{ proyecto.actividad_1 }} %
    <br />
    <b>Actividad 2 - Avance:</b> {{ proyecto.actividad_2 }} %
    <br />
    <br />
    <b>Avance total:</b>
    {{ proyecto.total }} %
    <div class="progress">
      <div class="progress-bar" role="progressbar" aria-valuenow="{{ proyecto.total }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ proyecto.total }}%;">
      </div>
    </div>
    <hr />
    <a href="{% url 'registro:editar' proyecto.id %}">
      <button class="btn btn-info">Editar</button>
    </a>
    <a href="{% url 'registro:borrar' proyecto.id %}">
      <button class="btn btn-danger">Borrar</button>
    </a>
  </div>
  {% endfor %}
  {% else %}
    <br />
    <b>No hay proyectos registrados aún</b>
  {% endif %}
{% endblock %}